### ISSUE TITLE
Doesn't auto split

### ISSUE THREAD

**Issue by esseivan** [sflofty/autosplitters#1] opened 2020-03-13 23:16 UTC
The autosplit doesn't work.
This is due to vars.loading never getting to false

adding : 
print(current.strokes_visible.ToString());

at the very start of isLoading shows that this value is always 0 and never 4.
Likely because the address offset is now invalid with the new version ?

I tried to bypass the !vars.loading in the split section and it works (except the loading of course)

**Comment by sflofty** [comment] 2020-03-15 19:02
hi @esseivan,
thanks for your comment. All I can say for now is, that the bug doesn't occur on my PC. 

However, I had other people tell me, that the splitter doesn't work for them. This issue might be the cause for this. I will look into this. :)

**Comment by sflofty** [comment] 2020-03-16 16:46
With your fix implemented, I asked three people if the splitter works. Unfortunately, it seems that there are still problems. For some it only splits on the first hole. For others, it doesn't split at all.

I am only a beginner, when it comes to memory adresses and pointers. Maybe the root cause lies here?

I will try to find different variables next and maybe come up with a more robust logik.

**Comment by esseivan** [comment] 2020-03-16 17:14
So it would be hole_finished_counter or current_hole, if the loading function is disabled via the setting.

I'm also beginning in cheat engine to find pointers and adresses, and btw how did you found a variable with value going from 2 for the main menu, to 4 for ingame (strokes_visible), and others for others cases ? Did you used the unknown initial value and then changed / unchanged value for the scan ? Or you knew a variable would get those specific values ?

Edit. assuming you're using cheat engine to find the pointers

**Comment by sflofty** [comment] 2020-03-16 19:15
Yes, i am using cheat engine. Since the timing for ingame time is exactly the same as the amount of time the stroke counter is visible, i tried to find a variable, that somewhat resembles wheather or not the counter is visible.

I think what I did was:
- I started in the menu and searched for "unknown value"
- Then "changed value", once the stroke count was visible
- Then "changed value" again everytime the state changed

note that when the ball is rolling, the stroke counter also changes colour, this might have an effect to the variable.

**Comment by sflofty** [comment] 2020-03-20 10:49
I overhauled the script. It now uses the time-left-on-hole in the top right corner to determin when the loading is complete. 

Now the script works for both runners I have asked so far. If it works for you aswell, I think this issue is solved.

On another note: If the script works, there is no use for the setting "pause on loading". I will remove it in a further version to prevent confusion for the user.

**Comment by esseivan** [comment] 2020-03-20 11:20
I just tried it and it worked fine
except that it didn't reset when I got back to main menu (either when it was running or finished), but that's not a big deal

**Comment by sflofty** [comment] 2020-03-20 11:33
hm, not resetting is weird, since it uses almost the same logik as used in "starting the timer"...
I will close this issue and open a new one for not resetting.

**Closed as completed by sflofty** 2020-03-20 11:33 UTC
